import React from 'react'
import ReactDOM from 'react'
import * as THREE from 'three'
import  'three/examples/js/vr/HelioWebXRPolyfill.js'
import Example from '-/components/example'
import notes from './readme.md'
import { VRButton } from 'three/examples/jsm/webxr/VRButton.js'
