name: GitHub Pages

on:
  push:
    branches:
    - v2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: npm install
    - run: npm run build
    - run: |
        git config --global user.name "Colin Schroeder"
        git config --global user.email "collin.schroeder@gmail.com"
        npm run push-gh-pages
